version: "3.7"

services:
  
  api:
    image: brmarques88/sre-api
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./python-sre/app/:/usr/src/sre/app/
    ports:
      - 5005:5000
    env_file:
      - ./python-sre/.env.dev
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
    environment:
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: flaskpwd

  web:
    image: brmarques88/sre-web
    ports:
      - "4201:4201"
    container_name: angular-sre
    volumes:
      - ./angular-sre:/usr/src/app/angular-sre
      - /usr/src/app/angular-sre/node_modules
    networks:
      - frontend

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    # volumes:
    #   - ./graylog/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: flaskuser
      MONGO_INITDB_ROOT_PASSWORD: flaskpwd
    networks:
      - backend

  mongo-graylog:
    image: mongo:4.2
    container_name: mongo-graylog
    networks:
      - graylog-network

  es-graylog:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: es-graylog
    environment:
      http.host: 0.0.0.0
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    networks:
      - graylog-network

  graylog:
    image: graylog/graylog:4.0
    container_name: graylog-sre
    restart: always
    environment:
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9001/
      GRAYLOG_MONGODB_URI: mongodb://mongo-graylog:27017/graylog
      GRAYLOG_ELASTICSEARCH_HOSTS: http://es-graylog:9200
      TZ: America/Sao_Paulo
    depends_on:
      - es-graylog
      - mongo-graylog
    ports:
      - 9001:9000
      - 12201:12201
      - 1514:1514
    networks:
      - backend
      - graylog-network
  
  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - network-zabbix
    ports:
      - "3307:3306"
    volumes:
      - "./zabbix/mysql:/var/lib/data"
    environment:
      - MYSQL_ROOT_PASSWORD=carryontech
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - "./zabbix/alertscripts:/usr/lib/zabbix/alertscripts"
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix
    restart: always
    ports:
      - "8087:8080"
      - "8443:8443"
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - mysql
      - zabbix-server
   
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-zabbix
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql
      - zabbix-server
      
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-5.0.1
    user: root
    networks:
      - network-zabbix
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.18.0.1
    depends_on:
      - zabbix-server    
               
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  network-zabbix:
    driver: bridge
  graylog-network:
    external: false